export const THEMES = {
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Executive Noir',
    desc: 'Matte obsidian felt with champagne gold & brushed aluminum accents',
    badge: 'Obsidian & Gold',
    pageBg: 'bg-gradient-to-b from-[#131822] via-[#090c10] to-[#090c10]',
    cardBg: 'bg-[#111620]/90 border-white/10',
    primaryBtn: 'bg-gradient-to-r from-amber-400 to-amber-500 hover:from-amber-300 hover:to-amber-400 text-gray-950',
    accentText: 'text-amber-400',
    accentTextLight: 'text-amber-300',
    accentBorder: 'border-amber-400/40',
    accentBg: 'bg-amber-400/15',
    accentRing: 'ring-amber-400/40',
    tableClass: 'poker-felt-noir',
  },
  emerald: {
    id: 'emerald',
    name: 'Monaco Emerald',
    desc: 'Deep classic European casino felt with mahogany leather rail',
    badge: 'Classic Green',
    pageBg: 'bg-gradient-to-b from-[#0c2617] via-[#05140c] to-[#05140c]',
    cardBg: 'bg-[#0b1f14]/90 border-emerald-500/20',
    primaryBtn: 'bg-gradient-to-r from-emerald-400 to-emerald-500 hover:from-emerald-300 hover:to-emerald-400 text-gray-950',
    accentText: 'text-emerald-400',
    accentTextLight: 'text-emerald-300',
    accentBorder: 'border-emerald-500/40',
    accentBg: 'bg-emerald-500/15',
    accentRing: 'ring-emerald-500/40',
    tableClass: 'poker-felt-emerald',
  },
  sapphire: {
    id: 'sapphire',
    name: 'High Roller Navy',
    desc: 'Royal midnight navy felt with brushed platinum trim',
    badge: 'Midnight Navy',
    pageBg: 'bg-gradient-to-b from-[#0d1c33] via-[#050b14] to-[#050b14]',
    cardBg: 'bg-[#0d1b2e]/90 border-blue-500/20',
    primaryBtn: 'bg-gradient-to-r from-blue-400 to-blue-500 hover:from-blue-300 hover:to-blue-400 text-gray-950',
    accentText: 'text-blue-400',
    accentTextLight: 'text-blue-300',
    accentBorder: 'border-blue-500/40',
    accentBg: 'bg-blue-500/15',
    accentRing: 'ring-blue-500/40',
    tableClass: 'poker-felt-sapphire',
  },
};
